### ISSUE TITLE
Bazel test fails with < Error: extra ';' [-Werror=pedantic] >

### ISSUE THREAD

**Issue by lustosa-leandro** [dliaomcp/fbstab#9]
The macro **FBSTAB_NO_COPY_NO_MOVE_NO_ASSIGN** defined in **copyable_macros.h** cannot be terminated with a semicolon if we are using **-Werror-pedantic** in my machine, otherwise it will not compile.

Maybe we should use **FBSTAB_NO_COPY_NO_MOVE_NO_ASSIGN** without terminating semicolon such as the other distinct but similar **FBSTAB_DEFAULT_COPY_AND_MOVE_AND_ASSIGN** macro instances I see in the project? 

Example of error output:

```shell
In file included from ./fbstab/fbstab_mpc.h:12:0,
                 from fbstab/fbstab_mpc.cc:1:
./fbstab/components/riccati_linear_solver.h:52:56: error: extra ';' [-Werror=pedantic]
   FBSTAB_NO_COPY_NO_MOVE_NO_ASSIGN(RiccatiLinearSolver);
                                                        ^
In file included from fbstab/fbstab_mpc.cc:1:0:
./fbstab/fbstab_mpc.h:62:46: error: extra ';' [-Werror=pedantic]
   FBSTAB_NO_COPY_NO_MOVE_NO_ASSIGN(FBstabMpc);
                                              ^
cc1plus: some warnings being treated as errors
```

**Comment by dliaomcp** [comment]
Fixed! I removed the extra semi-colons
